[package]
name = "rey-salvo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redis = "0.23.0"
salvo = "*"
tokio = { version = "1", features = ["macros"] }
tracing-subscriber = "0.3.17"
